galaxy_info:
  author: Efraim Vander
  description: Ansible role to automate and standardize Netplan configuration on Ubuntu
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

